name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Assign PR author
        run: |
          AUTHOR=$(jq -r .pull_request.user.login $GITHUB_EVENT_PATH)
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee @$AUTHOR

          # Define the reviewer based on the author
          case $AUTHOR in
            hanni66)
              REVIEWER=immyeong
              ;;
            immyeong)
              REVIEWER=Berygna
              ;;
            Berygna)
              REVIEWER=sshinylee
              ;;
            sshinylee)
              REVIEWER=cherry-go-round
              ;;
            cherry-go-round)
              REVIEWER=hanni66
              ;;
          esac

          # Assign the reviewer
          gh pr review-request ${{ github.event.pull_request.number }} --add @$REVIEWER
        env:
          GITHUB_TOKEN: ${{ secrets.REVIEW_TOKEN }}
